"""
backend/llm/model.py - Groq LLM API Wrapper for CampusAI

Provides robust LLM chat capabilities using the Groq API SDK with 
exponential backoff retries, request timeout enforcement, and custom exceptions.
"""

import time
from typing import List, Dict, Any, Optional
from groq import Groq, APIError, APIConnectionError, RateLimitError, APITimeoutError
from backend.config import settings
from backend.utils.logger import get_logger

logger = get_logger("campusai.llm.model")


class LLMUnavailable(Exception):
    """Custom exception raised when the Groq LLM service is unreachable or fails all retries."""
    pass


class GroqLLM:
    """Wrapper class for managing interactions with Groq LLM models."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
        timeout: float = 15.0,
        max_retries: int = 3
    ) -> None:
        """
        Initialize Groq LLM client instance.

        Args:
            api_key: Optional API key override. Defaults to config settings.
            model_name: Optional model override. Defaults to config settings.
            timeout: Request timeout limit in seconds (default: 15s).
            max_retries: Maximum number of retries before failing (default: 3).
        """
        self.api_key = api_key or settings.GROQ_API_KEY
        self.model_name = model_name or settings.GROQ_LLM_MODEL
        self.timeout = timeout
        self.max_retries = max_retries

        if not self.api_key or self.api_key.startswith("gsk_your_"):
            logger.warning("Groq API key is not configured properly.")

        self.client = Groq(
            api_key=self.api_key,
            timeout=self.timeout
        )

    def chat(
        self,
        messages: List[Dict[str, str]],
        temperature: float = 0.7,
        json_mode: bool = False,
        max_tokens: int = 500
    ) -> str:
        """
        Send a chat completion request to the Groq LLM API with retries and backoff.

        Args:
            messages: List of message dictionaries with 'role' and 'content'.
            temperature: LLM sampling temperature (0.0 to 1.0).
            json_mode: If True, forces JSON object response format.
            max_tokens: Maximum tokens in generated completion response.

        Returns:
            The string response generated by the model.

        Raises:
            LLMUnavailable: If the service fails after max retries or encounters unrecoverable errors.
        """
        response_format = {"type": "json_object"} if json_mode else None
        backoff = 1.5

        for attempt in range(1, self.max_retries + 1):
            try:
                logger.info(
                    "Sending LLM chat request (attempt %d/%d) using model %s",
                    attempt, self.max_retries, self.model_name
                )
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    response_format=response_format
                )

                if response.choices and len(response.choices) > 0:
                    reply_text = response.choices[0].message.content
                    if reply_text:
                        return reply_text.strip()
                    else:
                        raise LLMUnavailable("Received empty response content from Groq LLM API.")
                else:
                    raise LLMUnavailable("No choices returned from Groq LLM API response.")

            except (RateLimitError, APITimeoutError, APIConnectionError) as retryable_err:
                logger.warning(
                    "Groq API temporary error on attempt %d/%d: %s",
                    attempt, self.max_retries, str(retryable_err)
                )
                if attempt < self.max_retries:
                    logger.info("Retrying in %.1f seconds...", backoff)
                    time.sleep(backoff)
                    backoff *= 2.0
                else:
                    logger.error("Groq API failed after %d retries.", self.max_retries)
                    raise LLMUnavailable(
                        f"The AI service is temporarily unavailable due to network or rate limit issues: {str(retryable_err)}"
                    ) from retryable_err

            except APIError as api_err:
                logger.error("Groq API unrecoverable error: %s", str(api_err))
                raise LLMUnavailable(
                    f"Groq API error encountered: {str(api_err)}"
                ) from api_err

            except Exception as unk_err:
                logger.error("Unexpected error during LLM invocation: %s", str(unk_err))
                raise LLMUnavailable(
                    f"An unexpected error occurred while communicating with the AI service: {str(unk_err)}"
                ) from unk_err

        raise LLMUnavailable("Groq LLM service failed to respond.")
